// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWhiEFu9m7fPJ5y5S7yNaSlR0N9dd218k',
    appId: '1:347876786212:web:c387372e104416c71e58b1',
    messagingSenderId: '347876786212',
    projectId: 'footwear-aab73',
    authDomain: 'footwear-aab73.firebaseapp.com',
    storageBucket: 'footwear-aab73.appspot.com',
    measurementId: 'G-JZPTFMXF7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1gXZzqSyXAyJhSL49h6_MdWgLlPuyIyw',
    appId: '1:347876786212:android:66ef8759b63769681e58b1',
    messagingSenderId: '347876786212',
    projectId: 'footwear-aab73',
    storageBucket: 'footwear-aab73.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWhiEFu9m7fPJ5y5S7yNaSlR0N9dd218k',
    appId: '1:347876786212:web:4aee13d50317e8f11e58b1',
    messagingSenderId: '347876786212',
    projectId: 'footwear-aab73',
    authDomain: 'footwear-aab73.firebaseapp.com',
    storageBucket: 'footwear-aab73.appspot.com',
    measurementId: 'G-2YMC6Y371R',
  );
}
